#' ---
#' title: "Kidney Cancer Tables"
#' author: "Bokov"
#' date: "09/01/2017"
#' ---
#' 
#' Please read this file through before trying to run it. The comments tell
#' you what you need to edit in order to proceed.
#' 
#' ## Load libraries
#+ warning=FALSE, message=FALSE
rq_libs <- c(
             #'compiler'                              # just-in-time compilation
             #,'survival','MASS','Hmisc','zoo','coin' # various analysis methods
             'readr','dplyr','stringr','magrittr'   # data manipulation & piping
             ,'ggplot2','ggfortify','grid','GGally'  # plotting
             ,'stargazer','broom','janitor','tableone');                  # table formatting
rq_installed <- sapply(rq_libs,require,character.only=T);
rq_need <- names(rq_installed[!rq_installed]);
if(length(rq_need)>0) install.packages(rq_need,repos='https://cran.rstudio.com/',dependencies = T);
sapply(rq_need,require,character.only=T);
#' Turn JIT to max: pre-compile all closures, `for`, `while`, and `repeat` loops
#not needed yet
#enableJIT(3);
#' ## Load local config file
#' 
#' Please edit the file referenced below, it has instructions in the 
#' comments.
source('./config.R');
#' Please edit the file referenced below, it has instructions in the
#' comments
#not used yet
#source('./metadata.R');
#' This file has some possible useful functions. You might not need to edit
#' it but should read it.
source('./functions.R');

#'
#' ## Set generic variables
#' 
#' data dictionary:
#not needed yet
dctfile = '';
#' saved session data (not used right now)
#not needed yet
session <- 'session.rdata';

#' ## Load data if it exists 
#' 
#' (useful later, right now don't bother saving sessions)
if(session %in% list.files()) load(session);
#' Load your data. Notice that we're using `read_csv()` from the readr library.
#' It is a little smarter than the built-in `read.csv()`
d0 <- read_tsv(inputdata,na=c('(null)',''));
#' Read in the data dictionary
if(dctfile %in% list.files()) dct0 <- read_csv(dctfile,na = '');
#' ## Load data
#' 
#' This contains d0, which are counts by age, sex, and reference group
#load(inci_inputdata);
#' The inputdata is generated by the following bash command run on a collection 
#' of output files from chinotype:
#' `grep -H "^\"DEM|AGE\"" *.csv |awk -F, '{print $1 "," $2 "," $4 "," $5 "," $6 "," $7}'|sed -e "s/.csv:\"DEM|AGE\",\"DEM|AGE:/,/"|sed -e "s/\"//g" > kc_lc_agecounts.csv
`
#' 
d0 <- read.csv(inci_inputdata,header = F) %>% setNames(c('group','age','atrisk','frac_atrisk','cancer','frac_cancer'));
d0$agebin <- cut(d0$age,c(0,10*(2:7),Inf),include.lowest = T);
grepl()
#' ## First stage of tabulation
#' 
d0 %>% group_by(group,agebin) %>% 
  summarise(N=sum(atrisk),n=sum(cancer),pct=n/N) -> d1;

d1$sex <- d1$condition <- d1$group;
levels(d1$sex) <- levels(d1$group) %>% gsub('.*_f_.*','Female',.) %>% 
  gsub('.*_m_.*','Male',.) %>% ifelse(. %in% c('Male','Female'),.,' ');
levels(d1$cancer) <- levels(d1$cancer) %>% 
  ifelse(test=grepl('_kc$',.),yes='Kidney',no='Liver');
#' ## Age tables
#' 
cbind(
  subset(data.frame(d1),grepl('^nhw',group))
  ,subset(data.frame(d1),grepl('^hsp',group)));
#' ...and then I got lazy and copy-pasted to spreadsheet.
#' 
